name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  # build: # TODO
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v4
  image-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build container images from sources
        run: |
          cd src/game-2048
          docker build . --tag $CONTAINER_REGITRY_DOMAIN/$IMAGE_FOLDER/game-2048:${{ env.IMAGE_TAG }}
          cd ../cow-demo
          docker build . --tag $CONTAINER_REGITRY_DOMAIN/$IMAGE_FOLDER/cow-demo:${{ env.IMAGE_TAG }}
          cd ../redirect-server
          docker build . --tag $CONTAINER_REGITRY_DOMAIN/$IMAGE_FOLDER/redirect-server:${{ env.IMAGE_TAG }}
      - name: Scan game 2048 container image with NeuVector
        if: ${{ vars.USE_NEUVECTOR == 'true' }}
        uses: neuvector/scan-action@main
        with:
          image-repository: ${{ env.CONTAINER_REGITRY_DOMAIN }}/${{ env.IMAGE_FOLDER }}/game-2048
          image-tag: ${{ env.IMAGE_TAG }}
          min-high-cves-to-fail: "1"
          min-medium-cves-to-fail: "1"
      - name: Scan cow demo container image with NeuVector
        if: ${{ vars.USE_NEUVECTOR == 'true' }}
        uses: neuvector/scan-action@main
        with:
          image-repository: ${{ env.CONTAINER_REGITRY_DOMAIN }}/${{ env.IMAGE_FOLDER }}/cow-demo
          image-tag: ${{ env.IMAGE_TAG }}
          min-high-cves-to-fail: "1"
          min-medium-cves-to-fail: "1"
      - name: Scan redirect server container image with NeuVector
        if: ${{ vars.USE_NEUVECTOR == 'true' }}
        uses: neuvector/scan-action@main
        with:
          image-repository: ${{ env.CONTAINER_REGITRY_DOMAIN }}/${{ env.IMAGE_FOLDER }}/redirect-server
          image-tag: ${{ env.IMAGE_TAG }}
          min-high-cves-to-fail: "1"
          min-medium-cves-to-fail: "1"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CONTAINER_REGITRY_DOMAIN: docker.io
      IMAGE_FOLDER: ${{ vars.DOCKERHUB_NAMESPACE }}
      IMAGE_TAG: 2.0.${{ github.run_id }}
