name: PKG

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  runner-image-publication:
    name: "Image ${{ matrix.image-name }}"
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      matrix:
        image-name:
          - debian-node
          - ubuntu-dotnet
    uses: devpro/github-workflow-parts/.github/workflows/reusable-container-publication.yml@35750e9d1a21724d3a7e028ee9bc6da02dcb5afb
    with:
      container-registry: ghcr.io
      create-latest: ${{ github.ref_name == 'main' }}
      image-definition: src/${{ matrix.image-name }}/Dockerfile
      image-name: ${{ matrix.image-name }}
      image-path: ghcr.io/${{ github.repository_owner }}
      image-tag: "1.0.${{ github.run_id }}"
      image-platform: linux/amd64
      workflow-parts-version: 35750e9d1a21724d3a7e028ee9bc6da02dcb5afb
    secrets:
      container-registry-username: ${{ github.actor }}
      container-registry-password: ${{ secrets.GITHUB_TOKEN }}

  runner-image-publication-playwright:
    name: "Image debian-node-playwright"
    needs: runner-image-publication
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: devpro/github-workflow-parts/.github/workflows/reusable-container-publication.yml@35750e9d1a21724d3a7e028ee9bc6da02dcb5afb
    with:
      container-registry: ghcr.io
      create-latest: ${{ github.ref_name == 'main' }}
      extra-build-arguments: BASE_IMAGE=ghcr.io/${{ github.repository_owner }}/debian-node:1.0.${{ github.run_id }}
      image-definition: src/debian-node-playwright/Dockerfile
      image-name: debian-node-playwright
      image-path: ghcr.io/${{ github.repository_owner }}
      image-tag: "1.0.${{ github.run_id }}"
      image-platform: linux/amd64
      workflow-parts-version: 35750e9d1a21724d3a7e028ee9bc6da02dcb5afb
    secrets:
      container-registry-username: ${{ github.actor }}
      container-registry-password: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v7
      # TODO: secure first
      # - name: Login to container registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ env.CONTAINER_REGITRY_DOMAIN }}
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build container images
      #   run: |
      #     cd src/game-2048
      #     docker build . --tag $IMAGE_FOLDER/game-2048:${{ env.IMAGE_TAG }}
      #     cd ../cow-demo
      #     docker build . --tag $IMAGE_FOLDER/cow-demo:${{ env.IMAGE_TAG }}
      #     cd ../rancher-helloworld
      #     docker build . --tag $IMAGE_FOLDER/rancher-helloworld:${{ env.IMAGE_TAG }}
      #     cd ../redirect-server
      #     docker build . --tag $IMAGE_FOLDER/redirect-server:${{ env.IMAGE_TAG }}
      # - name: Push image to container registry
      #   run: |
      #     docker push $IMAGE_FOLDER/game-2048:${{ env.IMAGE_TAG }}
      #     docker push $IMAGE_FOLDER/cow-demo:${{ env.IMAGE_TAG }}
      #     docker push $IMAGE_FOLDER/rancher-helloworld:${{ env.IMAGE_TAG }}
      #     docker push $IMAGE_FOLDER/redirect-server:${{ env.IMAGE_TAG }}
      # - name: Push latest tag to container registry
      #   if: ${{ github.ref_name == 'main' }}
      #   run: |
      #     docker tag $IMAGE_FOLDER/game-2048:${{ env.IMAGE_TAG }} $IMAGE_FOLDER/game-2048:latest
      #     docker push $IMAGE_FOLDER/game-2048:latest
      #     docker tag $IMAGE_FOLDER/cow-demo:${{ env.IMAGE_TAG }} $IMAGE_FOLDER/cow-demo:latest
      #     docker push $IMAGE_FOLDER/cow-demo:latest
      #     docker tag $IMAGE_FOLDER/rancher-helloworld:${{ env.IMAGE_TAG }} $IMAGE_FOLDER/rancher-helloworld:latest
      #     docker push $IMAGE_FOLDER/rancher-helloworld:latest
      #     docker tag $IMAGE_FOLDER/redirect-server:${{ env.IMAGE_TAG }} $IMAGE_FOLDER/redirect-server:latest
      #     docker push $IMAGE_FOLDER/redirect-server:latest
    # env:
    #   CONTAINER_REGITRY_DOMAIN: docker.io
    #   IMAGE_FOLDER: ${{ vars.DOCKERHUB_NAMESPACE }}
    #   IMAGE_TAG: 1.0.${GITHUB_RUN_ID}
