name: PKG

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGITRY_DOMAIN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build container images
        run: |
          cd src/game-2048
          docker build . --tag $IMAGE_FOLDER/game-2048:${{ env.IMAGE_TAG }}
          cd ../cow-demo
          docker build . --tag $IMAGE_FOLDER/cow-demo:${{ env.IMAGE_TAG }}
          cd ../rancher-helloworld
          docker build . --tag $IMAGE_FOLDER/rancher-helloworld:${{ env.IMAGE_TAG }}
          cd ../redirect-server
          docker build . --tag $IMAGE_FOLDER/redirect-server:${{ env.IMAGE_TAG }}
      - name: Push image to container registry
        run: |
          docker push $IMAGE_FOLDER/game-2048:${{ env.IMAGE_TAG }}
          docker push $IMAGE_FOLDER/cow-demo:${{ env.IMAGE_TAG }}
          docker push $IMAGE_FOLDER/rancher-helloworld:${{ env.IMAGE_TAG }}
          docker push $IMAGE_FOLDER/redirect-server:${{ env.IMAGE_TAG }}
      - name: Push latest tag to container registry
        if: ${{ github.ref_name == 'main' }}
        run: |
          docker tag $IMAGE_FOLDER/game-2048:${{ env.IMAGE_TAG }} $IMAGE_FOLDER/game-2048:latest
          docker push $IMAGE_FOLDER/game-2048:latest
          docker tag $IMAGE_FOLDER/cow-demo:${{ env.IMAGE_TAG }} $IMAGE_FOLDER/cow-demo:latest
          docker push $IMAGE_FOLDER/cow-demo:latest
          docker tag $IMAGE_FOLDER/rancher-helloworld:${{ env.IMAGE_TAG }} $IMAGE_FOLDER/rancher-helloworld:latest
          docker push $IMAGE_FOLDER/rancher-helloworld:latest
          docker tag $IMAGE_FOLDER/redirect-server:${{ env.IMAGE_TAG }} $IMAGE_FOLDER/redirect-server:latest
          docker push $IMAGE_FOLDER/redirect-server:latest
    env:
      CONTAINER_REGITRY_DOMAIN: docker.io
      IMAGE_FOLDER: ${{ vars.DOCKERHUB_NAMESPACE }}
      IMAGE_TAG: 1.0.${GITHUB_RUN_ID}
