apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ctf-app
  namespace: ctf
  labels:
    app.kubernetes.io/name: ctf-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ctf-app
